import { Switch } from 'antd';
import Head from 'next/head';
import { FC, ReactElement } from 'react';
import { BrowserRouter } from 'react-router-dom';
import { IScaffoldAppProviders } from '~common/models';
import { MainPageFooter } from '~~/components/main/MainPageFooter';
import { MainPageHeader } from '~~/components/main/MainPageHeader';

interface ILayoutProps {
  ethPrice: number;
  scaffoldAppProviders: IScaffoldAppProviders;
  children?: ReactElement;
  notificationHolder: React.ReactElement;
}

export const Layout: FC<ILayoutProps> = (props) => {
  return (
    <div className="App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageHeader scaffoldAppProviders={props.scaffoldAppProviders} price={props.ethPrice} />
      {props.children}
      <MainPageFooter scaffoldAppProviders={props.scaffoldAppProviders} price={props.ethPrice} />
      <div style={{ position: 'absolute' }}>{props.notificationHolder}</div>
    </div>
  );
};
