# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request CI - NextJS & Hardhat

on:
  workflow_dispatch:
  push:
    branches: [release, next]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - name: 'Scaffold Configuration'
        run: |
          yarn create-config
          yarn set-react nextjs
          yarn set-solidity hardhat

      - name: 'Compile solidity'
        run: |
          yarn compile --force

      - name: 'Build contracts'
        run: |
          yarn contracts:build

      - name: 'Check hardhat run tasks'
        run: |
          yarn hardhat

      - name: 'Build nextjs production'
        run: |
          yarn cross-env NODE_OPTIONS=--max_old_space_size=4096 yarn build

      - name: 'Run tests'
        run: yarn test

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: testresult.xml
          comment_mode: update last
          hide_comments: all but latest
          compare_to_earlier_commit: true
          check_run_annotations: all tests, skipped tests
